import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

const kakaoApiKey = process.env.NEXT_PUBLIC_KAKAO_MAP_API_KEY;
const Kakao_SDK_URL = `https://dapi.kakao.com/v2/maps/sdk.js?appkey=${kakaoApiKey}&autoload=false`;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Script src={Kakao_SDK_URL} strategy="beforeInteractive" /> */}
        {children}
      </body>
    </html>
  );
}
